name: fragilista

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Run unit and linting tests
      run: make test-all
    
    - name: clean
      run: make clean